module.exports = {
  apps: [
    {
      name: 'mrst-api',
      cwd: '/home/ec2-user/projects/mrst/apps/api',
      script: 'src/index.ts',
      interpreter: '/home/ec2-user/projects/mrst/node_modules/.bin/tsx',
      env: {
        NODE_ENV: 'production',
        API_PORT: 3002,
        DATABASE_URL: 'postgresql://mrst:mrst_dev_2025@localhost:5432/mrst',
      },
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/ec2-user/projects/mrst/logs/api-error.log',
      out_file: '/home/ec2-user/projects/mrst/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'mrst-web',
      cwd: '/home/ec2-user/projects/mrst/apps/web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      env: {
        NODE_ENV: 'production',
        NEXT_PUBLIC_API_URL: 'https://app.travelautorental.com/api',
      },
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/ec2-user/projects/mrst/logs/web-error.log',
      out_file: '/home/ec2-user/projects/mrst/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'mrst-worker',
      cwd: '/home/ec2-user/projects/mrst/apps/worker',
      script: 'src/index.ts',
      interpreter: '/home/ec2-user/projects/mrst/node_modules/.bin/tsx',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://mrst:mrst_dev_2025@localhost:5432/mrst',
      },
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/ec2-user/projects/mrst/logs/worker-error.log',
      out_file: '/home/ec2-user/projects/mrst/logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
}
