/**
 * AI Intelligence Layer Tables
 *
 * Tables for embeddings, vector search, and AI processing
 */

import { pgTable, uuid, text, timestamp, integer, boolean, jsonb, index, unique } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'
import { tenants } from './platform'

/**
 * Custom vector type for pgvector
 * Using text type with casting since drizzle doesn't have native vector support
 */

/**
 * Embeddings for all content types
 * Stores vector embeddings for semantic search
 */
export const embeddings = pgTable('embeddings', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),

  // Source reference
  sourceType: text('source_type').notNull(), // 'timeline_event', 'gmail_message', 'monday_item', 'hq_reservation', 'customer', 'vehicle'
  sourceId: uuid('source_id').notNull(),

  // Content that was embedded
  content: text('content').notNull(),
  contentHash: text('content_hash').notNull(), // SHA256 for change detection

  // Embedding vector (1536 dimensions for OpenAI ada-002, 1024 for voyage-3)
  // Using text to store array, will cast to vector in queries
  embedding: text('embedding').notNull(),
  embeddingModel: text('embedding_model').notNull(), // 'voyage-3', 'text-embedding-3-small', etc.
  embeddingDimensions: integer('embedding_dimensions').notNull(),

  // Metadata for filtering
  metadata: jsonb('metadata').$type<{
    customerIds?: string[]
    vehicleIds?: string[]
    boardId?: string
    threadId?: string
    date?: string
    [key: string]: unknown
  }>(),

  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => [
  unique('embeddings_source').on(table.sourceType, table.sourceId),
  index('embeddings_tenant_id_idx').on(table.tenantId),
  index('embeddings_source_type_idx').on(table.sourceType),
  index('embeddings_content_hash_idx').on(table.contentHash),
  // Note: HNSW index on embedding column should be created via raw SQL migration:
  // CREATE INDEX embeddings_embedding_idx ON embeddings USING hnsw ((embedding::vector(1024)) vector_cosine_ops);
])

/**
 * AI conversations for chat/query history
 */
export const aiConversations = pgTable('ai_conversations', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  userId: uuid('user_id'),

  // Conversation context
  title: text('title'),
  context: jsonb('context').$type<{
    customerIds?: string[]
    vehicleIds?: string[]
    boardIds?: string[]
    dateRange?: { start: string; end: string }
  }>(),

  // Status
  isActive: boolean('is_active').notNull().default(true),

  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => [
  index('ai_conversations_tenant_id_idx').on(table.tenantId),
  index('ai_conversations_user_id_idx').on(table.userId),
])

/**
 * AI conversation messages
 */
export const aiMessages = pgTable('ai_messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id').notNull().references(() => aiConversations.id),

  // Message content
  role: text('role').notNull(), // 'user', 'assistant', 'system'
  content: text('content').notNull(),

  // For assistant messages: what sources were used
  sources: jsonb('sources').$type<Array<{
    type: string
    id: string
    title?: string
    relevance?: number
  }>>(),

  // Token usage
  promptTokens: integer('prompt_tokens'),
  completionTokens: integer('completion_tokens'),
  model: text('model'), // 'claude-3-opus', 'claude-3-sonnet', 'gemini-pro', etc.

  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (table) => [
  index('ai_messages_conversation_id_idx').on(table.conversationId),
  index('ai_messages_created_at_idx').on(table.createdAt),
])

/**
 * AI tasks/suggestions generated by the system
 */
export const aiTasks = pgTable('ai_tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),

  // Task details
  taskType: text('task_type').notNull(), // 'follow_up', 'action_required', 'anomaly', 'suggestion'
  priority: text('priority').notNull().default('medium'), // 'high', 'medium', 'low'
  title: text('title').notNull(),
  description: text('description').notNull(),
  reasoning: text('reasoning'), // AI's reasoning for this suggestion

  // Related entities
  relatedCustomerId: uuid('related_customer_id'),
  relatedVehicleId: uuid('related_vehicle_id'),
  relatedSources: jsonb('related_sources').$type<Array<{
    type: string
    id: string
  }>>(),

  // Status
  status: text('status').notNull().default('pending'), // 'pending', 'acknowledged', 'completed', 'dismissed'
  acknowledgedBy: uuid('acknowledged_by'),
  acknowledgedAt: timestamp('acknowledged_at'),
  completedAt: timestamp('completed_at'),
  dismissedAt: timestamp('dismissed_at'),
  dismissReason: text('dismiss_reason'),

  // Expiration
  expiresAt: timestamp('expires_at'),

  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => [
  index('ai_tasks_tenant_id_idx').on(table.tenantId),
  index('ai_tasks_status_idx').on(table.status),
  index('ai_tasks_priority_idx').on(table.priority),
  index('ai_tasks_task_type_idx').on(table.taskType),
  index('ai_tasks_customer_id_idx').on(table.relatedCustomerId),
  index('ai_tasks_vehicle_id_idx').on(table.relatedVehicleId),
])

/**
 * Content processing queue for embedding generation
 */
export const embeddingQueue = pgTable('embedding_queue', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),

  // Source to embed
  sourceType: text('source_type').notNull(),
  sourceId: uuid('source_id').notNull(),

  // Status
  status: text('status').notNull().default('pending'), // 'pending', 'processing', 'completed', 'failed'
  attempts: integer('attempts').notNull().default(0),
  lastError: text('last_error'),
  processedAt: timestamp('processed_at'),

  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (table) => [
  unique('embedding_queue_source').on(table.sourceType, table.sourceId),
  index('embedding_queue_status_idx').on(table.status),
  index('embedding_queue_created_at_idx').on(table.createdAt),
])

// Type exports
export type Embedding = typeof embeddings.$inferSelect
export type NewEmbedding = typeof embeddings.$inferInsert
export type AiConversation = typeof aiConversations.$inferSelect
export type NewAiConversation = typeof aiConversations.$inferInsert
export type AiMessage = typeof aiMessages.$inferSelect
export type NewAiMessage = typeof aiMessages.$inferInsert
export type AiTask = typeof aiTasks.$inferSelect
export type NewAiTask = typeof aiTasks.$inferInsert
export type EmbeddingQueueItem = typeof embeddingQueue.$inferSelect
export type NewEmbeddingQueueItem = typeof embeddingQueue.$inferInsert
